version: '3'
services:
  react:
    container_name: react-simple-project
    image: node-react-project
    tty: true
    restart: always
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/app
    working_dir: /app